from .basetrait import BaseTrait
from .sequencetrait import SequenceTrait
from .permutationtrait import PermutationSequenceTrait
from .binarytrait import BinaryTrait
from .binarysequencetrait import BinarySequenceTrait
from .inttrait import IntTrait
from .intsequencetrait import IntSequenceTrait
from .floattrait import FloatTrait
from .floatsequencetrait import FloatSequenceTrait
from .chartrait import CharTrait
from .charsequencetrait import CharSequenceTrait